title: HyunHo Bae
subtitle: 포토폴리오 겸 블로그
description: >- # this means to ignore newlines until "baseurl:"
#  devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is optimized for speed and readability.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
#    - text: Gallery
#      url: /gallery
#    - text: Shop
#      url : /shop
#    - text: Contact
#      url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: HyunHo Bae
author_bio: 안녕하세요 JAVA 개발자 배현호 입니다.
author_email: "gusgh555@naver.com"
author_location: Korea
author_website_url: "hyunhobae@gitbhnb.io"
typewrite-text: 포트폴리오 겸 메모용 블로그 입니다.
hero_cover_img: sample_cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: 와이드티엔에스
              company_logo: /와이드티엔에스 로고.jpg
              company_url: http://www.widetns.com/
              designation: 웹 개발자
              description: LG 협력사로 SI 및 SM 업무 수행
              visibility: true
            - company_name: JNDL
              company_logo: jndl logo.jpg
              company_url: http://www.jndcerti.com/index/
              designation: 전자파 시험원
              description: 전자파 시험원으로 근무
              visibility: false

# Education
author_education_details:
              - college_logo: hoseo logo.png
                college_name: 호서대학교
                college_url: https://www.hoseo.ac.kr/Home/Main.mbz
                college_degree: 기술 경영 학과
                description: 학사
                visibility: true

# Projects
author_project_details:
              - project_thumbnail:
                project_title: B2B 웹 서비스
                project_description: LG - 파트넌간 B2B 업무를 위한 내부 시스템 포털
                project_url:
                visibility: true
              - project_thumbnail: 지인몰.jpg
                project_title: 쇼핑몰 개발(Z:IN Mall)
                project_description: 현재 서비스 종료 됨
                project_url:
                visibility: true
# 자격증
author_certificate_details:
  -   certificate_title: 정보처리기사
      certificate_organ : 한국산업인력공단
      certificate_description:
      certificate_date: 2024.06
      visibility: true
  -   certificate_title: SQLD
      certificate_organ : 한국데이터베이스진흥센터
      certificate_description:
      certificate_date: 2024.09
      visibility: true
  -   certificate_title: NAVER Cloud Platform Certified Professional(NCP)
      certificate_organ : NAVER
      certificate_description:
      certificate_date: 2024.06
      visibility: true
  -   certificate_title: NAVER Cloud Platform Certified Associate(NCA)
      certificate_organ : NAVER
      certificate_description:
      certificate_date: 2024.06
      visibility: true
  -   certificate_title: Oracle Cloud Infrastructure 2024 Generative AI Certified Professional
      certificate_organ : Oracle
      certificate_description:
      certificate_date: 2024.06
      visibility: true
  -   certificate_title: 리눅스마스터2급
      certificate_organ : 한국정보통신인력개발센터
      certificate_description:
      certificate_date: 2024.06
      visibility: true



# social links
#twitter_username: xplor4r
github_username:  HyunHoBae
#instagram_username: xplor4r
# facebook_username: johndoe
# linkedin_username: johndoe
# behance_username: johndoe
# medium_username: johndoe
# telegram_username: johndoe
# dribbble_username: johndoe
# flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
# hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: HyunHoBae

# mailchimp embedded form url (newsletter):
mailchimp_form_url: #https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
formspree_email: gusgh555@naver.com

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true
show_author_certificate_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

  # jekyll admin is causing issues with github pages, so it's disabled by default
  # - jekyll-admin 

# Jekyll Admin Config
# jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  # homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
